# Generated by Django 4.1 on 2022-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_contact_user_gender_user_lastname_user_usertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_note', models.CharField(max_length=200)),
                ('about_us', models.CharField(max_length=1000)),
                ('footer_email', models.EmailField(max_length=254)),
                ('session_conduct', models.IntegerField(blank=True)),
                ('our_teachers', models.IntegerField(blank=True)),
                ('our_students', models.IntegerField(blank=True)),
                ('service_image', models.ImageField(blank=True, upload_to='serviceimage')),
                ('review_image', models.ImageField(blank=True, upload_to='reviewimage')),
                ('gallery_image', models.ImageField(blank=True, upload_to='galleryimage')),
            ],
        ),
    ]
