# Generated by Django 4.1 on 2022-10-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_website_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='website_settings',
            new_name='websiteSettings',
        ),
    ]
