# Generated by Django 4.1 on 2022-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_websitesettings_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='user_contact',
            field=models.IntegerField(default=0),
        ),
    ]
