# Generated by Django 4.1 on 2022-11-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_websitesettings_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='gallery_image',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='review_image',
        ),
    ]
