# Generated by Django 4.1 on 2022-11-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_websitesettings_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userclass',
            field=models.CharField(default='', max_length=200),
        ),
    ]
