# Generated by Django 4.1 on 2022-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usernote',
            field=models.CharField(default='', max_length=500),
        ),
    ]
