# Generated by Django 4.1 on 2022-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerimg', models.FileField(blank=True, null=True, upload_to='bannerimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
