# Generated by Django 4.1 on 2022-11-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bannerimg',
            field=models.ImageField(blank=True, null=True, upload_to='bannerimage'),
        ),
    ]
