# Generated by Django 4.1 on 2022-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_image_bannerimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertimg', models.ImageField(blank=True, null=True, upload_to='expertimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimg', models.ImageField(blank=True, null=True, upload_to='galleryimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
