# Generated by Django 4.1 on 2022-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_expertimage_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gardian_pic', models.ImageField(blank=True, null=True, upload_to='gardianpic')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gardian_comment', models.CharField(max_length=1000)),
                ('gardian_name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
