# Generated by Django 4.1 on 2022-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_pdf', models.FileField(blank=True, null=True, upload_to='uploadPdf')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
