# Generated by Django 4.1 on 2022-12-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_uploadpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcodeimg', models.ImageField(blank=True, null=True, upload_to='qrcodeimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
